remote_theme: pmarsceill/just-the-docs
footer_content: "Copyright &copy; 2020 Nick Mudge. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"